import type { Metadata } from "next";
// import { Geist, Geist_Mono, Fraunces } from "next/font/google";
import { Quicksand } from "next/font/google";
import "./globals.css";
import './custom.css';
import 'animate.css';

const quicksand = Quicksand({
  subsets: ['latin'],
  variable: '--font-quicksand',
  display: 'swap',
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Kandoo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
          className={`${quicksand.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
