import type { Metadata } from "next";
// import { Geist, Geist_Mono, Fraunces } from "next/font/google";
import { Inter } from 'next/font/google';
import { Fraunces } from "next/font/google";
import "./globals.css";
import './custom.css';
import 'animate.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

const fraunces = Fraunces({
  subsets: ['latin'],
  variable: '--font-fraunces',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Kandoo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
          className={`${inter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
